### ISSUE TITLE
To-Do Lists for README.md

### ISSUE THREAD

**Issue by hazrulakmal** [hazrulakmal/image-classification-KD#1]
WIP To-do List

- [x] Fixing display photo size
- [x] Installation Guide direct to publicto google colab
- [x] Notebook interface edits to use git clone
- [x] Codebase navigation touch up
- [x] Results touch up
- [x] Explain what went wrong with this study
- [x] check if running the google colab and kaggle notebook works.
- [x] add link to kaggle notebook
- [ ] percentage increase calculation
